### ISSUE TITLE
amplify publish needs "hosting add" and crashed when publish

### ISSUE THREAD

**Issue by vladimireduardo** [dabit3/gatsby-auth-starter-aws-amplify#1]
when i executed:
`amplify publish`
had an error: 
_Please add hosting to your project before publishing your project_

then i ran:
`amplify hosting add` 
and after 
`amplify publish` 

then ... another error ocurrs:

`
gatsby build

success open and validate gatsby-config — 0.008 s
success load plugins — 0.138 s
success onPreInit — 0.418 s
success delete html and css files from previous builds — 0.058 s
success initialize cache — 0.008 s
success copy gatsby files — 0.060 s
success onPreBootstrap — 0.003 s
success source and transform nodes — 0.016 s
success building schema — 0.169 s
success createPages — 0.005 s
success createPagesStatefully — 0.026 s
success onPreExtractQueries — 0.000 s
success update schema — 0.056 s
success extract queries from components — 0.032 s
success run graphql queries — 0.028 s — 6/6 223.35 queries/second
success write out page data — 0.003 s
success write out redirect data — 0.001 s
⢀ onPostBootstrapdone generating icons for manifest
success onPostBootstrap — 0.305 s

info bootstrap finished - 4.992 s

error Generating JavaScript bundles failed

  Error: ./node_modules/graphql/index.mjs 64:0-70:117
  Can't reexport the named export 'BREAK' from non EcmaScript module (only default export is available)
      at HarmonyExportImportedSpecifierDependency._getErrors (/Users/vladimirestrada/Documents/Code/brunoferrini/gatsby/gatsby-auth/node_modules/webpack/lib/dependencies/Harmo  nyExportImportedSpecifierDependency.js:344:6)
      at HarmonyExportImportedSpecifierDependency.getErrors (/Users/vladimirestrada/Documents/Code/brunoferrini/gatsby/gatsby-auth/node_modules/webpack/lib/dependencies/Harmon  yExportImportedSpecifierDependency.js:322:16)
      at Compilation.reportDependencyErrorsAndWarnings (/Users/vladimirestrada/Documents/Code/brunoferrini/gatsby/gatsby-auth/node_modules/webpack/lib/Compilation.js:1014:22)
      at Compilation.finish (/Users/vladimirestrada/Documents/Code/brunoferrini/gatsby/gatsby-auth/node_modules/webpack/lib/Compilation.js:832:9)
      at hooks.make.callAsync.err (/Users/vladimirestrada/Documents/Code/brunoferrini/gatsby/gatsby-auth/node_modules/webpack/lib/Compiler.js:492:17)
      at _err0 (eval at create (/Users/vladimirestrada/Documents/Code/brunoferrini/gatsby/gatsby-auth/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:11:1)
      at _addModuleChain (/Users/vladimirestrada/Documents/Code/brunoferrini/gatsby/gatsby-auth/node_modules/webpack/lib/Compilation.js:771:12)
      at processModuleDependencies.err (/Users/vladimirestrada/Documents/Code/brunoferrini/gatsby/gatsby-auth/node_modules/webpack/lib/Compilation.js:710:9)
      at _combinedTickCallback (internal/process/next_tick.js:131:7)
      at process._tickCallback (internal/process/next_tick.js:180:9)
   @ ./node_modules/@aws-amplify/api/lib/API.js
   @ ./node_modules/@aws-amplify/api/lib/index.js
   @ ./node_modules/aws-amplify/lib/index.js
   @ ./src/pages/index.js
   @ ./.cache/async-requires.js
   @ ./.cache/production-app.js
`

**Comment by dabit3** [comment]
Hey @vladimireduardo, thanks for the issue I'll check this out asap.

**Comment by stevelizcano** [comment]
First of all, thanks dabit3 for the boiler plate. It's a big help.

Amplify is also giving me the same issues, but is able to compile without problems. Running gatsby develop no longer is able to add accounts of login in, nothing happens with buttons. And using aws dev from the required AWS hosting gives an error which you can see here:

http://gatsbymplifyest-20180914145015--hostingbucket.s3-website-eu-west-1.amazonaws.com/

**Comment by dabit3** [comment]
Hey, @vladimireduardo @stevelizcano sorry about that, I just updated the readme with the correct info! I had left out a couple of steps. Apologies for any inconvenience.

**Comment by vladimireduardo** [comment]
> Hey, @vladimireduardo @stevelizcano sorry about that, I just updated the readme with the correct info! I had left out a couple of steps. Apologies for any inconvenience.

thanks a lot @dabit3 !
