### ISSUE TITLE
gatsby site will not start due to major error

### ISSUE THREAD

**Issue by marksteven** [dabit3/gatsby-auth-starter-aws-amplify#40]
H Nada,
Firstly thanks for the tutorials.
Have gone along on a few of theReact ones and they have been very informative.
Now moving to graphql and hit a wall.
Have tried 3 different times from scratch to install and run this project for amplify but keep getting various errors on gatsby locally after installing project. Will not run.
Initially there was graphql conflict saying 2 versions of grpahql in nodes so cannot start
deleted both present and reinstalled latest.
That error went away
then this that I have been unable to resolve.
Seems to be something with graphql conflicts reading some posts but cannot be sure

Using "gatsby develop" I get the following

success open and validate gatsby-configs - 0.027s
success load plugins - 0.939s
success onPreInit - 0.044s
success initialize cache - 0.025s
success copy gatsby files - 0.045s
success onPreBootstrap - 0.026s
success createSchemaCustomization - 0.008s
success Checking for changed pages - 0.002s
success source and transform nodes - 0.129s

 ERROR 

Missing onError handler for invocation 'building-schema', error was 'Error: Cannot create as TypeComposer the following value: Date.'. Stacktrace was 'Error: Cannot create as TypeComposer the following value: Date.
    at SchemaComposer.createTempTC (/Users/marksteven/Documents/sites/mytutorial-app/wildwood/node_modules/graphql-compose/lib/SchemaComposer.js:365:11)
    at SchemaComposer.addAsComposer (/Users/mark/Documents/sites/mytutorial-app/wildwood/node_modules/graphql-compose/lib/SchemaComposer.js:563:27)
    at createSchemaComposer (/Users/mark/Documents/sites/mytutorial-app/node_modules/gatsby/src/schema/schema-composer.js:16:18)
    at build (/Users/mark/Documents/sites/mytutorial-app/node_modules/gatsby/src/schema/index.js:104:26)
    at buildSchema (/Users/mark/Documents/sites/mytutorial-app/node_modules/gatsby/src/services/build-schema.ts:19:3)'

Hope this helps
Mark

**Comment by marksteven** [comment]
had another few added all dependancies again.
still no joy
getting these fatal errors
and boilerplate will not start.
 ERROR 

Missing onError handler for invocation 'building-schema', error was 'Error: Cannot create as TypeComposer the following value: Date.'. Stacktrace was 'Error: Cannot create as TypeComposer the following value: Date.

**Comment by nicolasheady** [comment]
I'm having same issues. Deleted package-lock.json and node_modules and reinstalled using npm, with no luck. I even installed all peer dependencies manually, no luck.

**Comment by marksteven** [comment]
I hear you.
Still trying to get any Gatsby project to work properly on AWS.
Fine locally and if I put it up on AWS via drag and drop also good
via Github continuous development it keeps failing
Fine until you add Auth to project.
Is yours working locally?
Lots of different theories on where the Auth files should go
Eg in Gatsby-browser or on the actual page only.
One thing that seems to be working better that you might want to try is 
not use withAuthentication but rather AmplifyAuthenticator from @aws-amplify/ui-react
Ill post here if I finally work it out.

**Comment by nicolasheady** [comment]
I did get it to work locally, but it will not deploy. I got it working locally by switching to installing with yarn instead of npm. But now it errors out when building the backend when I try to deploy on the Amplify Console. I get an "AccessDenied" error. Still working on this one.

**Comment by marksteven** [comment]
OK so same as me.
Im am on a conference call to AWS tech in few hours.
Will let you know how I go as he seems to think it should be OK

**Comment by marksteven** [comment]
Can you please maybe send me the log of the errors 
I will put that to him as well

**Comment by nicolasheady** [comment]
[log.txt](https://github.com/dabit3/gatsby-auth-starter-aws-amplify/files/5412885/log.txt)
I don't think there's any sensitive data in the log file? The only difference between the instructions for this starter Gatsby site and what I did, is I copied the repo into AWS code commit instead of using GitHub.

**Comment by marksteven** [comment]
Had a look. All good there but you have
The engine "node" is incompatible with this module. Expected version "^10.17.0 || ^12.0.0 || >= 13.7.0". Got "10.16.0"
2020-10-21T02:23:16.671Z [WARNING]: error Found incompatible module.

On your project
Go into amplify/backend/sometingsomethingcloudformation-template.yml
search node
If like me it says 10x
adjust that to read 12x
save
try again.

If not try in your build on AWS try
commands:
        - yarn install --ignore-engines
Might as well let you know what I have learned so far.
Even though your system is probably up to date for some reason it loads an old NodeJS
that should correct it and the build is something else I had partial success with

**Comment by nicolasheady** [comment]
Oh that was in there? That error has been coming and going, but I will give your fix a try for that.

**Comment by marksteven** [comment]
Hi Nicolas Seems it is very much in the build sequence. Also seems the technicians are currently in the process of updating the Gatsby interface on amplify so there might be some weird experiences over the coming weeks as well so keep in mind.
Anyway actually got it working using these build commands so give them a try (If you are using Yarn)
Also found out you need to be very careful editing the YML file so make sure the dashes line up exactly above each other as white space is seemingly counted in these types of file on AWS.
so copy and past exactly below. Will put up screen shot as well.
Cheers and good luck 
Mark

<img width="564" alt="Screen Shot 2020-10-21 at 10 56 43 pm" src="https://user-images.githubusercontent.com/3622273/96716530-dfa2cf80-13f0-11eb-922f-6d55943e918c.png">

version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - yarn --v      
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: public
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*

**Comment by nicolasheady** [comment]
Using just those build settings, I get both of these errors/warnings in the backend build:

(node:1961) UnhandledPromiseRejectionWarning: AccessDenied: Access Denied

apollo-upload-client@14.1.2: The engine "node" is incompatible with this module. Expected version "^10.17.0 || ^12.0.0 || >= 13.7.0". Got "10.16.0"

However, if I change the build settings to the below. I do not get the above errors, but I do get this error on the FRONTEND build:

error Generating JavaScript bundles failed
                                    Can't resolve '../aws-exports' in '/codebuild/output/src256105377/src/ripcodes/src/pages'

I do have the aws-exports file locally. But it is part of git ignore, and should be generated when building on the console.

Build Settings, as discussed here: https://github.com/aws-amplify/amplify-console/issues/1087

![buildsettings](https://user-images.githubusercontent.com/18339216/96731587-6ae67b80-1385-11eb-8926-c48256409909.png)

There are a lot of open and closed issues related to what I'm experiencing, I've been working through then trying the solutions and this is my most recent progress.

**Comment by marksteven** [comment]
try this for the engines
- yarn install--ignore-engines

**Comment by nicolasheady** [comment]
Well I cannot speak to what exactly solved my problem, but I pretty much recreated everything from scratch and now I've had minimal issues getting it running.
